### ISSUE TITLE
text-davinci-003 deprecated error

### ISSUE THREAD

**Issue by HannahMR** [Roasbeef/LangChainL402#3]
Running LangChainBitcoin now returns the below error...

“openai.error.InvalidRequestError: The model `text-davinci-003` has been deprecated” 

It seems that the version of LangChain being used needs to be updated. I was able to update the version of LangChain being used from 0.0.205 to 0.1.13. That change also required changes to several other dependencies. 

Updated: langchain 0.0.205 → 0.1.13
Updated: openai 0.27.6 → 1.10.0,<2.0.0
Updated: packaging 23.1 → 23.2,<24.0
Updated: typing_extensions 4.5.0 → 4.7,<5
Changes: platformdirs 3.6.0 → 2.6.2
Added: langchain-openai 0.1.1

With these changes the requirements can be installed without error, and the program can be run without receiving the text-davinci-003 deprecated error, however, some of the context for the prompts has been lost. 

The API documentation in API_DOCS is being understood, but the prompt given via chain_new.run() is not. It seems that chain_new.run should be updated to chain_new.invoke, but that there will be other changes needed as well. 

I suspect that what is being imported in the l402_api_chain.py file will need to be updated as well, but I haven’t found the solution just yet.

**Comment by Roasbeef** [comment]
Ah yeh, they deprecated that old model. I think now GPT 3.5 turbo is the new base model.

**Comment by Roasbeef** [comment]
Fixed by https://github.com/lightninglabs/LangChainBitcoin/pull/4
